ALTER TABLE "GeneralSettings"
  ADD COLUMN "deliveryFree" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "deliveryInsideDhaka" DOUBLE PRECISION NOT NULL DEFAULT 60,
  ADD COLUMN "deliveryOutsideDhaka" DOUBLE PRECISION NOT NULL DEFAULT 120;
