-- Migration: Add salary fields to User table
ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "basicSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "overtime"    DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "ta"          DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "bonus"       DOUBLE PRECISION NOT NULL DEFAULT 0;
